// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import AchievementHighlightController from "./achievement_highlight_controller";
application.register("achievement-highlight", AchievementHighlightController);

import AddressSelectController from "./address_select_controller";
application.register("address-select", AddressSelectController);

import BioEditorController from "./bio_editor_controller";
application.register("bio-editor", BioEditorController);

import CommandPaletteController from "./command_palette_controller";
application.register("command-palette", CommandPaletteController);

import ComposerController from "./composer_controller";
application.register("composer", ComposerController);

import EmojiPickerController from "./emoji_picker_controller";
application.register("emoji-picker", EmojiPickerController);

import CountdownClockController from "./countdown_clock_controller";
application.register("countdown-clock", CountdownClockController);

import CurveDrawController from "./curve_draw_controller";
application.register("curve-draw", CurveDrawController);

import CustomsWarningController from "./customs_warning_controller";
application.register("customs-warning", CustomsWarningController);

import DecisionTreeController from "./decision_tree_controller";
application.register("decision-tree", DecisionTreeController);

import DevlogReviewController from "./devlog_review_controller";
application.register("devlog-review", DevlogReviewController);

import DevlogTimeChartController from "./devlog_time_chart_controller";
application.register("devlog-time-chart", DevlogTimeChartController);

import DialogueIterationController from "./dialogue_iteration_controller";
application.register("dialogue-iteration", DialogueIterationController);

import DisabledTooltipController from "./disabled_tooltip_controller";
application.register("disabled-tooltip", DisabledTooltipController);

import DropdownController from "./dropdown_controller";
application.register("dropdown", DropdownController);

import FallingStarController from "./falling_star_controller";
application.register("falling-star", FallingStarController);

import FaqAccordionController from "./faq_accordion_controller";
application.register("faq-accordion", FaqAccordionController);

import FileUploadController from "./file_upload_controller";
application.register("file-upload", FileUploadController);

import StarImageInputController from "./star_image_input_controller";
application.register("star-image-input", StarImageInputController);

import FlashController from "./flash_controller";
application.register("flash", FlashController);

import FormSubmitOnceController from "./form_submit_once_controller";
application.register("form-submit-once", FormSubmitOnceController);

import FraudReportController from "./fraud_report_controller";
application.register("fraud-report", FraudReportController);

import GithubCalendarController from "./github_calendar_controller";
application.register("github-calendar", GithubCalendarController);

import HackatimeLinkController from "./hackatime_link_controller";
application.register("hackatime-link", HackatimeLinkController);

import HackatimeProjectSelectorController from "./hackatime_project_selector_controller";
application.register(
  "hackatime-project-selector",
  HackatimeProjectSelectorController,
);

import HcbChartController from "./hcb_chart_controller";
application.register("hcb-chart", HcbChartController);

import HeroWarpController from "./hero_warp_controller";
application.register("hero-warp", HeroWarpController);

import JsonHighlightController from "./json_highlight_controller";
application.register("json-highlight", JsonHighlightController);

import LazyLoadController from "./lazy_load_controller";
application.register("lazy-load", LazyLoadController);

import LockedTabController from "./locked_tab_controller";
application.register("locked-tab", LockedTabController);

import MarkdownPreviewController from "./markdown_preview_controller";
application.register("markdown-preview", MarkdownPreviewController);

import MediaViewerController from "./media_viewer_controller";
application.register("media-viewer", MediaViewerController);

import ModalController from "./modal_controller";
application.register("modal", ModalController);

import OnboardingInterestsController from "./onboarding_interests_controller";
application.register("onboarding-interests", OnboardingInterestsController);

import OnboardingTransitionController from "./onboarding_transition_controller";
application.register("onboarding-transition", OnboardingTransitionController);

import OrderFormController from "./order_form_controller";
application.register("order-form", OrderFormController);

import ParallaxController from "./parallax_controller";
application.register("parallax", ParallaxController);

import PrizeFloatController from "./prize_float_controller";
application.register("prize-float", PrizeFloatController);

import ProfileEditController from "./profile_edit_controller";
application.register("profile-edit", ProfileEditController);

import ProfileModalController from "./profile_modal_controller";
application.register("profile-modal", ProfileModalController);

import ProjectCreationController from "./project_creation_controller";
application.register("project-creation", ProjectCreationController);

import ProjectFormController from "./project_form_controller";
application.register("project-form", ProjectFormController);

import ProjectThumbsLoopController from "./project_thumbs_loop_controller";
application.register("project-thumbs-loop", ProjectThumbsLoopController);

import ProjectThumbsScrollController from "./project_thumbs_scroll_controller";
application.register("project-thumbs-scroll", ProjectThumbsScrollController);

import ReadmeImageController from "./readme_image_controller";
application.register("readme-image", ReadmeImageController);

import RevealOnScrollController from "./reveal_on_scroll_controller";
application.register("reveal-on-scroll", RevealOnScrollController);

import ReviewSidebarController from "./review_sidebar_controller";
application.register("review-sidebar", ReviewSidebarController);

import RocketArcController from "./rocket_arc_controller";
application.register("rocket-arc", RocketArcController);

import RsvpCounterController from "./rsvp_counter_controller";
application.register("rsvp-counter", RsvpCounterController);

import SearchableSelectController from "./searchable_select_controller";
application.register("searchable-select", SearchableSelectController);

import ShopController from "./shop_controller";
application.register("shop", ShopController);

import ShopGoalsController from "./shop_goals_controller";
application.register("shop-goals", ShopGoalsController);

import ShopWishlistController from "./shop_wishlist_controller";
application.register("shop-wishlist", ShopWishlistController);

import SidebarActiveController from "./sidebar_active_controller";
application.register("sidebar-active", SidebarActiveController);

import CountUpController from "./count_up_controller";
application.register("count-up", CountUpController);

import UpgradeModalController from "./upgrade_modal_controller";
application.register("upgrade-modal", UpgradeModalController);

import Tilt3dController from "./tilt_3d_controller";
application.register("tilt-3d", Tilt3dController);

import TooltipController from "./tooltip_controller";
application.register("tooltip", TooltipController);

import TutorialVideoModalController from "./tutorial_video_modal_controller";
application.register("tutorial-video-modal", TutorialVideoModalController);

import UserRefModalController from "./user_ref_modal_controller";
application.register("user-ref-modal", UserRefModalController);

import VimeoPlayerController from "./vimeo_player_controller";
application.register("vimeo-player", VimeoPlayerController);

import WelcomeTourController from "./welcome_tour_controller";
application.register("welcome-tour", WelcomeTourController);

import WhatIsThisController from "./what_is_this_controller";
application.register("what-is-this", WhatIsThisController);

import WordCountController from "./word_count_controller";
application.register("word-count", WordCountController);

import WordCycleController from "./word_cycle_controller";
application.register("word-cycle", WordCycleController);
